package gui.chess;

public enum PieceTypes {

    BLACK_KING(1), BLACK_QUEEN(1), BLACK_ROOK1(1),BLACK_ROOK2(1), BLACK_BISHOP1(1),BLACK_BISHOP2(1), BLACK_KNIGHT1(1), BLACK_KNIGHT2(1), BLACK_PAWN1(1), BLACK_PAWN2(1), BLACK_PAWN3(1),
    BLACK_PAWN4(1), BLACK_PAWN5(1), BLACK_PAWN6(1), BLACK_PAWN7(1), BLACK_PAWN8(1),
    WHITE_KING(-1), WHITE_QUEEN(-1), WHITE_ROOK1(-1),WHITE_ROOK2(-1), WHITE_BISHOP1(-1), WHITE_BISHOP2(-1),WHITE_KNIGHT1(-1),WHITE_KNIGHT2(-1), WHITE_PAWN1(-1),WHITE_PAWN2(-1),WHITE_PAWN3(-1),
    WHITE_PAWN4(-1),WHITE_PAWN5(-1),WHITE_PAWN6(-1),WHITE_PAWN7(-1),WHITE_PAWN8(-1);

    final int moveDirection;

    PieceTypes(int moveDirection) {

        this.moveDirection = moveDirection;

    }

} // end class PieceTypes.
